### ISSUE TITLE
从计算机历史开始记录

### ISSUE THREAD

**Issue by Forrest-IT** [Forrest-IT/it-memories#1]
IT 历史的开端，应该要从计算机的历史开始记录。

**Comment by Joshua-Chow** [comment]
这是一个非常有趣、值得关注的小事业。只有当一位工程师能够充分了解历史的时候，才能够认清楚未来所要走的方向和要付出自己全部精力而奋斗的事业！

加油！⛽️

**Comment by Forrest-IT** [comment]
> 这是一个非常有趣、值得关注的小事业。只有当一位工程师能够充分了解历史的时候，才能够认清楚未来所要走的方向和要付出自己全部精力而奋斗的事业！
> 
> 加油！⛽️

我之前通过维基百科、BBC 纪录片了解过数学的发展历史，之后就对数学有了很清楚的认知，逐渐喜欢上数学。我想作为一名计算机工程师、软件开发工程师也应该去了解计算机理论基础、计算机硬件、计算机软件的发展历史。

**Comment by Joshua-Chow** [comment]
> > 这是一个非常有趣、值得关注的小事业。只有当一位工程师能够充分了解历史的时候，才能够认清楚未来所要走的方向和要付出自己全部精力而奋斗的事业！
> > 加油！⛽️
> 
> 我之前通过维基百科、BBC 纪录片了解过数学的发展历史，之后就对数学有了很清楚的认知，逐渐喜欢上数学。我想作为一名计算机工程师、软件开发工程师也应该去了解计算机理论基础、计算机硬件、计算机软件的发展历史。

是的，不妨在业余时间进行这方面知识的积累！祝好！ @Forrest-IT

**Comment by Forrest-IT** [comment]
> > > 这是一个非常有趣、值得关注的小事业。只有当一位工程师能够充分了解历史的时候，才能够认清楚未来所要走的方向和要付出自己全部精力而奋斗的事业！
> > > 加油！⛽️
> > 
> > 
> > 我之前通过维基百科、BBC 纪录片了解过数学的发展历史，之后就对数学有了很清楚的认知，逐渐喜欢上数学。我想作为一名计算机工程师、软件开发工程师也应该去了解计算机理论基础、计算机硬件、计算机软件的发展历史。
> 
> 是的，不妨在业余时间进行这方面知识的积累！祝好！ @Forrest-IT

谢谢，我会努力的！
